const express = require('express');
const TaskController = require('../controllers/TaskController');
const router = express.Router();
router.post('/', TaskController.login);
router.get('/tabla', TaskController.tabla);
router.get('/obtenerprop/:sector', TaskController.obtenerPropuestas);
router.post('/prop', TaskController.prop);
router.get('/view/:id', TaskController.view);
router.get('/edit/:id', TaskController.edit);
router.post('/edit/:id', TaskController.update);
router.get('/proposal/:sector', TaskController.proposal);
router.post('/proposal/:sector', TaskController.storeProposal);
router.get('/propuestas', TaskController.propuestas);
router.get('/votes', TaskController.votes);
router.get('/vote/:id', TaskController.vote);
router.get('/reset', TaskController.reset);
router.get('/resetp', TaskController.resetp);
router.get('/register', TaskController.register);
router.get('/inicio', TaskController.inicio);
router.post('/register', TaskController.store);
router.get('/tasks', TaskController.index);
router.get('/prueba', TaskController.prueba);
router.get('/listar', TaskController.listar);

module.exports = router;